### ISSUE TITLE
Starting teamocil after running tmux?

### ISSUE THREAD

**Issue by andyph666** [remiprev/teamocil#105]
I'm trying to get teamocil to start when starting tmux. I'm running i3-gaps and cannot manage to get teamocil to load a config automatically when running tmux. Thanks!

**Comment by remiprev** [comment]
This is more of a `tmux` question than Teamocil. Unfortunately, I never had to do something like that, but looks like some people have ideas how to do it:

https://www.google.com/#q=tmux+run+command+on+startup

**Comment by remiprev** [comment]
I’m going to close this issue.
