### ISSUE TITLE
dir root for new windows?

### ISSUE THREAD

**Issue by niksfirefly** [remiprev/teamocil#107]
after upgrade to 1.4 i notice that i cannot set root dir for new panes?
is there a way to bring back this behaviour?

**Comment by remiprev** [comment]
Can you paste 1) the YAML content of the layout you’re running here **and** 2) the output of `teamocil --debug <layout_name>`. Thank you!

**Comment by niksfirefly** [comment]
ok i found out that starting in tmux 1.9 the default-path option was removed
so i bind
bind c new-window -c "#{pane_current_path}"
in tmux 2.0 and now it works
