### ISSUE TITLE
Running teamocil configs multiple times

### ISSUE THREAD

**Issue by nblumoe** [remiprev/teamocil#111]
Hey, not should if this is a bug or if anything can be easily done about this, but I would like to run a teamocil config multiple times in parallel. This does not work, presumably because of colliding window names. I tried using `teamocil --here my_config.yml` but this did not help at all.

So should I be able to run `teamocil my_config.yml`  in multiple tmux windows independently?

**Comment by remiprev** [comment]
@nblumoe You’re right, at this moment Teamocil doesn’t support running the same layout multiple times in a single session. However, this is not something I think is a popular use case among users. What I suggest you do is create copies of the layout and make sure each one has a unique window name 😄 

I’m going to close this issue.
