### ISSUE TITLE
feature: auto-generate layout file from currently running tmux session

### ISSUE THREAD

**Issue by gardiner** [remiprev/teamocil#32]
Just like "pip freeze" - freezes the currently visible tmux layout into a layout file skeleton. Would greatly simplify layout setup...

Anyway - teamocil is a great tool, don't want to miss it :) Thanks!

**Comment by scientist1642** [comment]
Hi @remiprev,
Your comment about getting current layout from terminal is super helpful! 
What do you think mentioning this trick in the README? as I think MANY people would like to have custom layout (saying that we can use tmux splitting and `:resize-pane` commands as we like and then save the custom layout)

**Comment by remiprev** [comment]
@scientist1642 Yeah, I think it was in the `README.md` before the 1.0 rewrite. I’ll add it back 😄

**Comment by remiprev** [comment]
@scientist1642 Done! https://github.com/remiprev/teamocil/commit/7f8a47f6632d2aeff683c71a3ed3d5cfdd3a87a1

**Comment by scientist1642** [comment]
@remiprev cool! 🎉
