### ISSUE TITLE
how to specify another root of configure instead ~/.teamocil

### ISSUE THREAD

**Issue by metrue** [remiprev/teamocil#90]
is that OK to put the configure into other place more the ~/.teamocil ?

**Comment by remiprev** [comment]
There’s a `--layout` command line option that you can use

| Option | Description
|-----------|-------------------------
| `--layout` | Takes a custom file path to a YAML layout file instead of `[layout-name]`

```bash
$ teamocil --layout /path/to/layout/file.yml
```

**Comment by metrue** [comment]
@remiprev 

thanks, nice README, how come I missed that part.
Great tool, thanks.
