### ISSUE TITLE
run tmux automatically if it's not running 

### ISSUE THREAD

**Issue by bubenkoff** [remiprev/teamocil#92]
For simplicity of use, i think it makes sense to automatically ensure tmux is running

**Comment by pklingem** [comment]
+1

**Comment by remiprev** [comment]
Thanks for the suggestion, but `teamocil` is a tool to use within `tmux`. It makes the assumption that `tmux` is running and I don’t want `teamocil` to have the task of launching `tmux` if it’s not.

**Comment by lins05** [comment]
You can simply do it like this:

```sh
    tmux attach || tmux new-session -d "teamocil sample" \; attach
```

I wraps this in a shell function to save keystokes:

```sh
ttt () 
{ 
    tmux -L bg attach || tmux -L bg new-session -d "teamocil sample" \; attach
}
```

**Comment by remiprev** [comment]
@lins05 Thanks for the tip!
