### ISSUE TITLE
Error with --edit option

### ISSUE THREAD

**Issue by billypon** [remiprev/teamocil#96]
When I run "teamocil --edit xxx", I get this error: "sh: 1: /path/to/.teamocil/xxx.yml: Permission denied".

But when I run "vim ~/.teamocil/xxx.yml", it works fine!

When I run "echo $EDITOR", I got "vim".

tmux version 1.9a, teamocil 1.2

**Comment by remiprev** [comment]
I don’t know what’s going on… Is the error you’re getting actually has `/path/to` in it?

```
sh: 1: /path/to/.teamocil/xxx.yml: Permission denied
```

Also, could you run this command:

```bash
$ ruby -e 'system("echo $EDITOR")'
```

To make sure the `$EDITOR` bash variable is available in Ruby scripts.

**Comment by billypon** [comment]
@remiprev After I run command `ruby -e 'system("echo $EDITOR")'`, I still got that error

**Comment by billypon** [comment]
@remiprev I found the way to solve this problem: $EDITOR need to set as `full path`, like `/usr/bin/vim`. Thanks

**Comment by billypon** [comment]
@remiprev I found I need to reset EDITOR like `export EDITOR=\`echo $EDITOR\``, or I will got that error.

**Comment by billypon** [comment]
@remiprev My shell is `zsh`, I found teamocil use `sh` to call $EDITOR. And the variable in `sh` is empty.

**Comment by billypon** [comment]
@remiprev Now the problem is solved. I added `export EDITOR=vim` to `.profile`

**Comment by remiprev** [comment]
Cool, I’m going to close the issue now.

**Comment by idkjs** [comment]
In fishshell:
```bash
// ~/.config/fish/config.fish
set -gx EDITOR nvim
```

gets rid of error on running `teamocil -edit sample`

```bash
~/Downloads
 [I] ➜ teamocil --edit sample
sh: /Users/mandalarian/.teamocil/sample.yml: Permission denied
```
