### ISSUE TITLE
Set the options for layouts

### ISSUE THREAD

**Issue by Taluu** [remiprev/teamocil#98]
Unless I read it wrong, we cannot currently set some additional options for the layout property of the yaml file.

I'm referring to the options for the main-* layouts, such as `main-pane-height` for the `main-horizontal` layout (or respectively `main-pane-width` for the `main-vertical` layout). Or be able to modify the window option ?

**Comment by andyph666** [comment]
I was wondering the same thing. It would be very useful if we could change the layout positions of the panels. Thanks.

**Comment by remiprev** [comment]
You’re right, this would be a pretty useful option to add. I’m a big user of the `main-vertical` layout myself and never thought of using the `main-pane-width` option.

I’m on it!

**Comment by remiprev** [comment]
@Taluu @andyph666 The `options` key for windows is now working in `tmux-1.4` :grinning:

**Comment by Taluu** [comment]
I guess you meant `teamocil-1.4` but cool :D

**Comment by remiprev** [comment]
Heh indeed!

**Comment by Taluu** [comment]
Mmh, seems not to be working :

```bash
tmux rename-session 'Foo'
tmux send-keys -t 'Vim.0' 'cd "/home/talus/dev/foo"'
tmux send-keys -t 'Vim.0' 'Enter'
tmux rename-window 'Vim'
tmux set-window-option -t 'Vim' main-pane-height 500
tmux send-keys -t 'Vim.0' 'vim'
tmux send-keys -t 'Vim.0' 'Enter'
tmux select-layout -t 'Vim' 'main-horizontal'
tmux split-window -t 'Vim' -c '/home/talus/dev/foo'
tmux send-keys -t 'Vim.1' 'foo'
tmux send-keys -t 'Vim.1' 'Enter'
tmux select-layout -t 'Vim' 'main-horizontal'
tmux split-window -t 'Vim' -c '/home/talus/dev/foo'
tmux send-keys -t 'Vim.2' 'tail -f my.log'
tmux send-keys -t 'Vim.2' 'Enter'
tmux select-layout -t 'Vim' 'main-horizontal'
tmux select-pane -t Vim.0
```

I got the "pane too small" problem. I guess it is because the `set-window-option` is sent too soon ?
